[theme]
primaryColor = '#1b1464'  # Cor do tema principal (pode ajustar)
backgroundColor = '#f0f2f6'  # Cor de fundo da aplicação
secondaryBackgroundColor = '#ffffff'  # Cor secundária de fundo
textColor = '#000000'  # Cor do texto

[server]
headless = true
port = $PORT
enableCORS = false
